### ISSUE TITLE
How to connect to parity on different machine

### ISSUE THREAD

**Issue by stasbar** [parity-js/shell#102]
> I'm running:
>
> - **Parity client version**: Parity/v1.10.3-stable-b9ceda3-20180507/arm-linux-gnu/rustc1.25.0
> - **Parity UI version**: 0.1.1
> - **Operating system**: MacOS
> - **Installed via**: installer
> - **Fully synchronized**: no 
> - **Network**: ethereum 
> - **I tried to restart both Parity UI and Parity Ethereum client**:  yes

Hello, how to connect to parity client running on the different machine? Previously I connected via 192.168.0.xxx:8180 but now I need to connect via this app. I don't see an option to enter different URL

**Comment by Tbaut** [comment]
You can specify the Websocket IP and Websocket port that the Parity UI will use by launching `parity-ui` with the following flags
```bash
    --ws-interface=[IP]
        Specify the hostname portion of the WebSockets server 
        Parity UI will connect to. IP should be an 
        interface's IP address. (default: 127.0.0.1)

    --ws-port=[PORT]
        Specify the port portion of the WebSockets 
        server Parity UI will connect to. (default: 8546)
```
