### ISSUE TITLE
Editing the metadata of a wallet corrupts the JSON key

### ISSUE THREAD

**Issue by Tbaut** [parity-js/shell#106]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 1.11.1
> - **Parity UI version**: 0.2.2
> - **Operating system**: Linux
> - **Installed via**: binaries
> - **Fully synchronized**: not relevant
> - **Network**: tested on ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

Before editing the metadata:
```
$ cat ~/.local/share/io.parity.ethereum/keys/ethereum/UTC--2018-04-20T12-29-51Z--4d99d2c6-85da-1dcc-f4db-0bd75e12f6d5 
{"id":"4d99d2c6-85da-1dcc-f4db-0bd75e12f6d5","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"3f4e63966d6f5...689f240a"},"ciphertext":"ab0c0bcd78199a...669d7a40df7fbce","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"83acee02...db150d68"},"mac":"22763026...22e0b"},"address":"00bde63c2...4d332fb6060","name":"Signer Test 001","meta":"{\"description\":\"\",\"passwordHint\":\"whatever\",\"tags\":[],\"timestamp\":1524227384857}"}
```

After editing to the wallet's metadata (name, decription, hint), im my case this example, changing the name `Signer Test 001` to `Signer Oops 001`:
```
$ cat ~/.local/share/io.parity.ethereum/keys/ethereum/UTC--2018-04-20T12-29-51Z--4d99d2c6-85da-1dcc-f4db-0bd75e12f6d5 
{"id":"4d99d2c6-85da-1dcc-f4db-0bd75e12f6d5","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"3f4e63966d6f5...689f240a"},"ciphertext":"ab0c0bcd78199a...669d7a40df7fbce","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"83acee02...db150d68"},"mac":"22763026...22e0b"},"address":"00bde63c2...4d332fb6060","name":"Signer Oops 001","meta":"{\"description\":\"\",\"passwordHint\":\"whatever\",\"tags\":[],\"timestamp\":1524227384857}"}57}"}
```
Note at the end how `57}"}` was added and made the JSON invalid

Steps to reproduce:
- In Parity Wallet>Account>Select an account and `EDIT` 
- Change the name/description/hint click on `SAVE`

The corruption **doesn't always happens**. Repeating the operation, the name of the wallet sometimes changes in the UI, sometimes not, the key file gets edited, sometimes not...

**Comment by axelchalon** [comment]
Might be due to a race condition
![image](https://user-images.githubusercontent.com/5739676/40080628-d6c6c330-588b-11e8-8a86-57e2aea73ae8.png)
