### ISSUE TITLE
Parity UI getting crashed everytime

### ISSUE THREAD

**Issue by sayan1886** [parity-js/shell#119]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 0.0.0
> - **Parity UI version**: 0.2.4
> - **Operating system**: MacOS
> - **Installed via**: installer
> - **Fully synchronized**: no
> - **Network**: ethereum / ropsten / kovan / ...
> - **I tried to restart both Parity UI and Parity Ethereum client**: no / yes

_Your issue description goes here below. Parity UI getting crashed after downloading parity.

<img width="1198" alt="screen shot 2018-05-24 at 9 31 06 pm" src="https://user-images.githubusercontent.com/680974/40497457-db1b1886-5f99-11e8-804b-c7ebf718c0db.png">

**Comment by amaurymartiny** [comment]
I will have a look into this issue.

Could you paste the content of `/Users/sayanchatterjee/Library/Application\ Support/parity-ui/parity.log`?

Thanks.

**Comment by felixbrucker** [comment]
I experienced the same on Windows 8.1 x64, the log file is empty and when i try to execute the parity.exe manually windows tells me the program can't be executed on my PC.

**Comment by amaurymartiny** [comment]
For debug purposes, could you try:
- make sure no other Parity instance in running
- remove the binary `/Users/sayanchatterjee/Library/Application\ Support/parity-ui/parity` (in AppData for windows)
- launch Parity UI again

This will allow Parity UI to have a clean start.

---

Alternatively, you could run Parity in another terminal, and run Parity UI with the `--no-run-parity` flag, this will tell the UI not to launch another instance of parity.

**Comment by axelchalon** [comment]
FWIW I have this issue on [fether](https://github.com/paritytech/fether) when the program tries to run Fether after downloading it

**Comment by axelchalon** [comment]
Looks like this is due to an incomplete download of Parity by Parity UI. Like Amaury said, removing the Parity binary downloaded by Parity UI and re-launching Parity UI sould fix the problem
