### ISSUE TITLE
Unable to connect to my remote parity node via parity-ui.

### ISSUE THREAD

**Issue by Alko89** [parity-js/shell#124]
I'm unable to connect to my remote parity node via parity-ui and am unable to access my tokens since the browser UI is depricated.

Whenever I try to connect to parity with the new UI, I get to the `parity signer new-token` message and am unable to continue (I've generated the token a milion times now).

> I'm running:
>
> - **Parity client version**: 1.10.4
> - **Parity UI version**: None from the release works
> - **Operating system**: Linux
> - **Installed via**: binaries
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

When toggling developer mode in parity-ui, I can see this error:
`WebSocket connection to 'ws://192.168.10.80:8180/' failed: Error during WebSocket handshake: Unexpected response code: 200`

**Comment by Tbaut** [comment]
You seem to launch the ui with a non common ws port. Can you tell how you launch your parity node and the UI?
We strongly advise connecting to the remote node with [ssh tunneling](https://wiki.parity.io/Wallet-Remote-Access#recommended-ssh-tunneling). The UI does not need any specific flag if you use the standard ports.

**Comment by Alko89** [comment]
I launch parity using a systemd service:
```
[Unit]
Description=Parity Daemon
After=network.target

[Service]
User=alko
ExecStart=/usr/bin/parity

[Install]
WantedBy=default.target
```
Here is my `config.toml`:
```
[parity]

[ui]
interface = "192.168.10.80"

#[network]
#min_peers = 5
#max_peers = 10

[rpc]
interface = "192.168.10.80" 

[websockets]
interface = "192.168.10.80" 
origins = ["all"]
```

I added origins later with no effect.

I also tried configuring a reverse proxy with Nginx from the same link (commenting out interfaces in `config.yaml`) with the same result.

I'll try SSH tunneling now.

**Comment by Tbaut** [comment]
Thanks for the details. Please delete the `[ui]` part from your toml as you do not use it (Parity UI is a standalone UI). You seem not to have specified any custom WS indeed, your default port should be 8546. Launching `parity-ui`, it should use it by default, not sure why it tried to connect to 8180.

Doing a SSH tunneling as pointed above should get you where you want without even needing any `interface` from your config file as rpc and ws interface will be tunneled to your localhost.

**Comment by Alko89** [comment]
Sorry for the late reply. I have made it work with over SSH. I might keep using it that way. I like it, thanks!

Should I keep the issue open? I guess this is still a bug.

**Comment by Tbaut** [comment]
The UI will be totally removed in v1.12 so I'll close the issue as not really relevant anymore.
