### ISSUE TITLE
Request failed with status code 521

### ISSUE THREAD

**Issue by vieiralc** [parity-js/shell#125]
Before filing a new issue, please provide the following information.

I'm running:

Which Parity version?: v1.10.4-20180514 stable
Which operating system?: Windows 32bits
How installed?: via installer
Are you fully synchronized?: no
Which network are you connected to?: dev
Did you try to restart the node?: yes
Your issue description goes here below. Try to include actual vs. expected behavior and steps to reproduce the issue.

image
![image](https://user-images.githubusercontent.com/19657718/40733502-299426f8-640c-11e8-8e30-c24df0613efc.png)

**Comment by amaurymartiny** [comment]
Ah, this might be our Vanity service (from where the UI fetches parity) which was down for a couple of moments.

Right now it [seems up](https://vanity-service.parity.io/parity-binaries?version=beta&os=windows&architecture=x86_64), could you please retry?
