### ISSUE TITLE
Search is visually broken and difficult to use

### ISSUE THREAD

**Issue by lampshade9909** [parity-js/shell#128]
> I'm running:
>
> - **Parity client version**: Parity v1.10.2-20180423 beta
> - **Parity UI version**: Version 0.1.1 (0.1.1)
> - **Operating system**: MacOS
> - **Installed via**: installer
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

The search feature is visually broken.  It's not intuitive and doesn't function as any user would expect.  I would expect it to show results once I type in something and hit enter.  It seems that I have to click on the search button, type in something, then click around and escape search mode in order for it to display results.  Then it's not obvious that the results are filtered and you have to click on search again and clear what you typed then click on the search button again in order to clear the results back to normal.  

Showing results as I type would be a nice to have.  Automatically putting the cursor in the search box when I do a Command+F or a Control+F would be lovely as well.  

<img width="1173" alt="screen shot 2018-05-30 at 11 42 11 am" src="https://user-images.githubusercontent.com/5184617/40740802-9f4aea5c-63fe-11e8-9f33-171ba6d96a1b.png">

**Comment by axelchalon** [comment]
Hi @lampshade9909, we could not reproduce this issue. The search results should show up as you type. Were you maybe accessing Parity UI with your web browser? Can you reproduce this issue when browsing your wallet inside the Parity UI application, with the latest version?
