### ISSUE TITLE
Token not accepted if base-path of parity folder is non-standard

### ISSUE THREAD

**Issue by theBergmann** [parity-js/shell#131]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 1.10.6
> - **Parity UI version**: 0.1.2
> - **Operating system**:  Linux
> - **Installed via**: snap
> - **Fully synchronized**: yes
> - **Network**: ethereum 
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

I use Parity with a --base-path flag. Need to do, because it has grown too big for my main drive.

When I start the parity-ui it doesn't accept the token, no matter how often I try.

When I start Parity without the --base-path flag, it accepts the token. So the source of the error should be clear. But how can I fix it?

**Comment by Tbaut** [comment]
Thanks for the report. To make sure there is no misunderstanding: what do you mean by "it accepts the token"?
Can you open the developer console of Parity UI and reproduce what you do when the problem happens and post a screenshot of the console here? (use ctrl-shift-i or command-option-i on mac)

**Comment by theBergmann** [comment]
Thank you for the response

"accept the token" means that I am able to access the wallet. 
When I use the alternative base-path, it just shows the token request again.

While using the console, I solved my problem: I had to run the command "parity signer new-token" with the base-path flag. After it it worked!

**Comment by Tbaut** [comment]
Understood, you were talking about the UI token :)
