### ISSUE TITLE
parameterize the url

### ISSUE THREAD

**Issue by oneroot001** [parity-js/shell#132]
the node url can be parameterized so that we can connect to other node.
change http://localhost:8545 to config string

**Comment by petri** [comment]
The websocket port is already parametrized (--ws-interface and --ws-port). Being able to specify host and port also for JSON-RPC is an essential feature.

**Comment by amaurymartiny** [comment]
The WS port is parameterized, and Parity UI is making JSONRPC calls solely via WS.

A port for JSON-RPC (I assume you're suggesting via HTTP transport) is not necessary.

**Comment by petri** [comment]
@amaurymartiny however the web3 console within Parity-UI is not communicating via WS is it? 

I wonder if the same applies to some other 'tools' available in Parity-UI as well ...?

**Comment by amaurymartiny** [comment]
The Web3 Console and all other tools -we call them dapps at Parity- are communicating with the node via WS.

To be more exact, the dapps are not communicating with the node directly. Here's the flow:
- the dapps send their JSONRPC request to the shell
- the shell receives the request, checks that the dapp has the permission to make that JSONRPC call (or shows an orange bar at the bottom to ask for permission)
- if the dapp indeed has the correct permission, then the shell relays this call to the node, via WS

Do no hesitate to ask more if it's still not clear.

**Comment by petri** [comment]
Thank you @amaurymartiny . Can you then explain why Parity-UI 0.2.5 and web3 dapp certainly seem to require RPC access via port 8545 as in:

I have a remote Parity node I'm connecting to via SSH tunnels (both for WS port & JSONRPC port). Parity-UI starts normally.

BUT when I close the tunnel for port 8545 and restart Parity-UI:

- I see "cannot fetch node health" in Parity UI
- when starting up the web3 dapp, I see Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545/rpc/

Please advise.

**Comment by amaurymartiny** [comment]
Ah sorry, you are right, the Web3 console is also making calls to the node directly [via HTTP](https://github.com/parity-js/dapp-console/blob/6a48e07ce930443c72f93032c45186db7753db33/src/parity.js#L33).

Namely:
- `web3.eth.coinbase()` will make an HTTP call from the dapp to the node (bypassing the shell)
- `api.eth.coinbase()` will make a call via the mechanism described above

which might be confusing.

---

Back to the original issue: Parity UI still doesn't need a parameter for jsonrpc HTTP host+port. If you run Parity with `--jsonrpc-port 1234`, then the Web3 console will make a HTTP call to http://localhost:1234/rpc/.
