### ISSUE TITLE
Uncaught Exception when launching UI first time

### ISSUE THREAD

**Issue by spolrot** [parity-js/shell#133]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 1.11.3
> - **Parity UI version**: 0.2.5
> - **Operating system**: MacOS High Sierra 10.13.5
> - **Installed via**: installer
> - **Fully synchronized**: no
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

First opening of the UI, the following error message appears:

> Uncaught Exception:
> Error: spawn EACCES
>     at _errnoException (util.js:1024:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at exports.spawn (child_process.js:514:9)
>     at module.exports (/Applications/Parity UI.app/Contents/Resources/app.asar/.build/electron.js:15266:22)
>     at EventEmitter.module.exports (/Applications/Parity UI.app/Contents/Resources/app.asar/.build/electron.js:14782:9)
>     at emitTwo (events.js:126:13)
>     at EventEmitter.emit (events.js:214:7)
>     at WebContents.<anonymous> (/Applications/Parity UI.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
>     at emitTwo (events.js:126:13)
>     at WebContents.emit (events.js:214:7)

The message only appears on the first launch.

**Comment by amaurymartiny** [comment]
Will be fixed in the next version 0.3.0.
