### ISSUE TITLE
Missing Wallet icon

### ISSUE THREAD

**Issue by catageek** [parity-js/shell#134]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: Parity v1.12.0-20180606 unstable
> - **Parity UI version**: 0.2.5
> - **Operating system**: Linux
> - **Installed via**: from source
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

**actual**

- see all Dapps icons except wallet
- all dapps working except wallet

**expected behavior**

- see all Dapps icons
- all dapps working including wallet

**steps to reproduce**

- clone the UI repo
- cd git && git checkout v0.2.5
- execute 'npm install'
- execute 'npm run electron'

**Comment by axelchalon** [comment]
If you clone the UI repo and use the `master` branch now, the wallet should be there again.

**Comment by catageek** [comment]
It worked. Thank you
