### ISSUE TITLE
ParityUI is connecting to the global network if local parity is not running

### ISSUE THREAD

**Issue by Pzixel** [parity-js/shell#142]
> I'm running:
>
> - **Parity client version**: -
> - **Parity UI version**: 0.1.4
> - **Operating system**: Windows
> - **Installed via**: installer
> - **Fully synchronized**: -
> - **Network**: -
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

I faced an issue that when local node is not available ParityUI after 5 sec delay just connects to the global network. It's an undesirable behavior. Could it be changed?

**Comment by Tbaut** [comment]
It's actually a feature. What's the problem with that?

**Comment by Pzixel** [comment]
It suddenly takes 40gb on hard drive when it's unintended.

**Comment by amaurymartiny** [comment]
From Parity UI versions 0.2 there is an additional flag `--no-run-parity`. This will tell the UI not to run a local instance of parity.
