### ISSUE TITLE
Dapp sometimes doesn't load (inject.js not loaded in time)

### ISSUE THREAD

**Issue by axelchalon** [parity-js/shell#145]
To reproduce:
- `npm run electron`
- open dev console
- open dapp "Dapp Method Permissions"

You get `Uncaught Error: Unable to locate EthereumProvider, object not attached` the first time. When refreshing the page or coming back to the homepage and then back again to the dapp, the dapp works fine.

Actually happens quite often.

My intuition was that `inject.js` wasn't necessarily loaded before the dapp (because of async `readFile`), that this caused a race condition and the dapp to throw `Uncaught Error: Unable to locate EthereumProvider, object not attached` or similar errors if its js was run before inject.js. I thought using `readFileSync` [here](https://github.com/parity-js/shell/blob/master/src/preload.js#L32) would fix it but it doesn't.. seems like we can't rely on `webFrame.executeJavaScript` to be run immediately? then I tried replacing the whole of  `preload.js` with `throw new Error('test')` and turns out the error doesn't even systematically show up when we get `Uncaught Error: Unable to locate EthereumProvider, object not attached`, even though electron's preload script is supposed to be first thing to be executed in the webview... I'm floored... any idea @amaurymartiny ?

**Comment by amaurymartiny** [comment]
I actually reproed this a couple of times too, but only on opening the 1st dapp. Opening subsequent dapps works fine. And never managed to repro on the binaries, so I let it pass.

But you're right, this should definitely be handled deterministically.

I'm not sure how to achieve this neither. The only slight hint of an idea I have is:
- Don't put the `url` field in the webview inside `dapp.js`, but still instantiate the `<webview>` tag.
- Try to get the `webview` instance inside the preload script (if that's even possible)
- `webFrame.executeJavaScript` taked a callback argument, and on that callback, do [`webview.loadUrl`](https://electronjs.org/docs/api/webview-tag#webviewloadurlurl-options).

@axelchalon I think the best would actually be to post an issue on the electron repo. Could you take care of that?

**Comment by axelchalon** [comment]
It seems to me that `inject.js` is not loaded in time only when the DevTools are open when navigating to the dapp. It shouldn't be too much of an issue then.

**Comment by neo35** [comment]
Das entfernten inject.funzioniert oder github Team ?

**Comment by neo35** [comment]
Problem gelöst ;)

**Comment by axelchalon** [comment]
I think we can close this for now
