### ISSUE TITLE
How to Launch/Use Parity UI

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#148]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 1.10
> - **Which Parity UI Version?**: Parity UI (also confusingly called Parity-JS): Parity UI v0.1.4-stable
> - **Which operating system?**: Debian
> - **How installed?**: via .deb
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes
_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I installed Parity UI from binary.

Now what?  There are no instructions.  Well there are but the instruction is literally "Launch Parity UI" and that is not telling me how.

https://wiki.parity.io/Parity-Wallet

The desired result is that I go to localhost:8180 and see the familiar Parity UI interface.

**Comment by Tbaut** [comment]
Localhost:8180 is not accessible anymore since v1.10. 
You should be able to launch parity-ui the way you would launch any other application. Either with you app launcher or in the command line: `parity-ui`

**Comment by stone212** [comment]
@Tbaut 

> Either with you app launcher

This is not some GUI system I am using.  I run a headless Parity server and I need access to the UI remotely (using an SSH tunnel).  Parity is not a desktop application now is it?  It is a server process and runs on headless servers.

**Comment by stone212** [comment]
> in the command line: parity-ui

I recommend you add this to the wiki.  A user should not have to go through an Issue to learn this after installing.  I found it by a search of the filesystem but that also should not be required.
