### ISSUE TITLE
Parity UI begins to download Parity on first run without promting

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#149]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: N/A
> - **Parity UI version**: 0.2.7
> - **Operating system**: Linux
> - **Installed via**: binary (deb)
> - **Fully synchronized**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When I run parity-ui on a client that does not have an established SSH tunnel the Parity UI begins to download Parity without asking first.  

A better UX might be if an error comes up saying "Parity UI does not detect the Parity RPC.  Do you want to establish an SSH tunnel to a Parity server or do you want to download Parity and run a node locally?"

**Comment by Tbaut** [comment]
You can make sure that Parity UI does not try to run the node by launching it with `--no-run-parity`.
I don't agree with your propositions. If you are savvy enough to run an SSH tunnel, then you can launch it with `--no-run-parity`. I wouldn't call it "a better UX" to start with an error message and talk about SSH :)

**Comment by stone212** [comment]
@Tbaut Than you for replying.  There are two things I disagree with:

1. The default behavior of any application should never be to download something without a prompt.  Unless the executable is named "downloadThisWithoutAnyPrompting.sh"

2.  That flag was not known.  I am going to be pendantic to make my point: You are saying that after searching for something on Parity UI and after learning that it's actually called Parity JS and after searching for Parity JS on the wiki and after finding nothing and after submitting an issue and after you sent a link to https://wiki.parity.io/Wallet-Remote-Access.html and after reading that page *which does not mention this flag or anything else about how to run the UI* that if the sys admin is "savvy" enough then he will magically know the flag that you mentioned?

You might say that all I had to do is run parity-ui with the -h flag.  Putting away the fact that I had to guess that the exectuable is "parity-ui" there is also that *nothing* in that output suggests that the `--no-run-parity` flag will prevent parity-ui from installing parity.  Here is what it says:

```--no-run-parity      Parity UI will not attempt to run the locally installed parity.```

Nowhere does it mention downloading Parity node software.  To "run the locally installed parity" is not the same as "install parity locally".


I agree with your main point: because there is a flag that does this then that is better than my proposition.  

As usual with Parity the issue isn't bad code.  It's that you release code without complete (or in this case any) doc.

**Comment by Tbaut** [comment]
PR welcome, we're open source!

**Comment by stone212** [comment]
> PR welcome, our sources are open!

Now you're just replying to reply.  What does allowing pull requests have to do with writing accurate docementaion?  I specifically said that the code is not the problem at Parity.  The belief that a product can be released before writing documentation is the problem.
