### ISSUE TITLE
Parity App missing from the Parity UI

### ISSUE THREAD

**Issue by chevdor** [parity-js/shell#161]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: Parity v1.12.0-20180630 unstable
> - **Parity UI version**: Version 0.2.7 (0.2.7)
> - **Operating system**: Windows / **MacOS** / Linux
> - **Installed via**: installer / snap / **binaries** / from source
> - **Fully synchronized**: no / **yes**
> - **Network**: ethereum / ropsten / **kovan** / ...
> - **I tried to restart both Parity UI and Parity Ethereum client**: no / **yes**

No Parity Wallet available:
![image](https://user-images.githubusercontent.com/738724/42561108-afb06d02-84f8-11e8-9687-d25ab58f2226.png)

**Comment by axelchalon** [comment]
hey @chevdor! to fix this you can either use a version of Parity inferior to v1.12 ; or use Parity v1.12 with Parity UI on `master` (or use the new release of Parity UI that we will make in the next few days)

**Comment by chevdor** [comment]
@axelchalon thanks for the update.
I confirm, with the latest parity UI 0.3.0, that Parity is back.
