### ISSUE TITLE
Feature Request: clear cache/refresh

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#167]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 1.10.8
> - **Parity UI version**: 0.2.7
> - **Operating system**: Ubuntu Linux
> - **Installed via**: .deb
> - **Fully synchronized**: yes
> - **Network**: private blockchain
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

It could be useful to be able to refresh the WebUI as with a browser hitting F5.  Clearing cache.  It is useful in at least two situations:

1. When you connect to a different Parity node (ssh tunnel)

2. When you make a change like adding or remove a key.

**Comment by Tbaut** [comment]
You can use CTRL-R to do so.

**Comment by stone212** [comment]
@Tbaut That does not seem to have the same effect as closing and re-starting the parity-ui.  Are you sure that CTRL-R clears the cache?  In a browser it does not.  It only refreshes.

**Comment by Tbaut** [comment]
Ctrl-Shift-R to reload the cache IMO.

**Comment by stone212** [comment]
Not sure what IMO means.  Does Ctrl-Shift-R reload the cache or not?  I will try next time I have this problem.

**Comment by stone212** [comment]
@Tbaut Yes that seems to work for at least one application.  Thank you.
