### ISSUE TITLE
Installed from PKG, iMAC Error

### ISSUE THREAD

**Issue by mgbvox** [parity-js/shell#172]
> - **Parity client version**: Parity/v1.9.7
> - **Parity UI version**: 0.3.0
> - **Operating system**: MacOS
> - **Installed via**: installer
> - **Fully synchronized**: no
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

Downloaded Parity-UI .pkg file from latest releases link. Installer ran according to plan, but got this message when attempting to open the app:
```
Please attach the following debugging info:
OS: darwin
Arch: x64
Channel: beta
Error: Cannot read property 'webContents' of undefined
Please also attach the contents of the following file:
/Users/mgb/Library/Application Support/parity-ui/parity.log

Please quit the app and retry again. If the error message persists, please file an issue at https://github.com/parity-js/shell/issues."
```

So... I'm doing what it told me.

**Comment by Tbaut** [comment]
Thanks for the report. Could you also paste the content of `/Users/mgb/Library/Application Support/parity-ui/parity.log`

**Comment by mgbvox** [comment]
<img width="229" alt="screen shot 2018-07-16 at 10 36 23 am" src="https://user-images.githubusercontent.com/26420601/42764717-4d64b460-88e4-11e8-8438-c8f0743f9c3c.png">

There appears not to be a parity.log file in that directory.

**Comment by axelchalon** [comment]
hi @mgbvox, could you paste the error that appears in your terminal when you launch Parity UI?

working on a fix: https://github.com/parity-js/shell/pull/173

**Comment by mgbvox** [comment]
@axelchalon, as far as I can tell, launching Parity from the console (i.e. typing 'parity' and hitting return) works fine - I'm already at QED now.

**Comment by mgbvox** [comment]
Is there a different command for launching the UI from the console specifically?

**Comment by Tbaut** [comment]
> Is there a different command for launching the UI from the console specifically?

Yes, most probably `/Users/mgb/Library/Application Support/parity-ui/parity-ui`

**Comment by mgbvox** [comment]
When I type that into the terminal I get:
-bash: /Users/mgb/Library/Application Support/parity-ui/parity-ui: No such file or directory

**Comment by conorfennell** [comment]
I have the exact same behaviour.
If you do this from terminal
`cd /Applications/Parity\ UI.app/Contents/MacOS/`
then
`./Parity\ UI`

Then you can launch from the command line; it doesn't help the situation but at least you know how to do it 🤷‍♂️

**Comment by conorfennell** [comment]
Great news, the following release fixes the issue: https://github.com/parity-js/shell/releases/tag/v0.3.2

Now with a caveat, I have my own node running, so I had to start the Parity ui like so
`./Parity\ UI --no-run-parity`
from this folder
`cd /Applications/Parity\ UI.app/Contents/MacOS/`
