### ISSUE TITLE
failed to create symbolic link

### ISSUE THREAD

**Issue by indigoram89** [parity-js/shell#178]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 2.0.0-beta
> - **Parity UI version**: 0.2.8 / 0.3.2
> - **Operating system**: Linux Ubuntu 18.04
> - **Installed via**: snap
> - **Fully synchronized**: yes
> - **Network**: ropsten
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

``` bash
parity-ui
```

``` bash
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Documents': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Desktop': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Downloads': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Music': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Pictures': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Videos': No such file or directory
ln: failed to create symbolic link '/home/user/snap/parity-ui/31/snap/parity-ui/31/Templates': No such file or directory

```

**Comment by Tbaut** [comment]
Thanks for the report. Please try installing the UI with installers or the binaries instead of snap that is causing a lot of troubles.

**Comment by indigoram89** [comment]
@Tbaut thank you! But I don't understand how I can to do It on Ubuntu server...

**Comment by Tbaut** [comment]
Parity UI is supposed to run on the client and connect to a remote node/server (for instance using [SSH tunneling](https://wiki.parity.io/Wallet-Remote-Access.html#ssh-tunneling---recommended)). I don't know your setup but it looks like you want to install it on a remote headless server.

**Comment by indigoram89** [comment]
I will try it and let you know. Thank you for your answer!

**Comment by indigoram89** [comment]
When I launch the Parity UI application on my mac, It also starts the local parity node.

How can I use the Parity UI application with the node on a remote server?

**Comment by Tbaut** [comment]
Answered in #181 I will close this issue.
