### ISSUE TITLE
Contracts menu item is invisible

### ISSUE THREAD

**Issue by indigoram89** [parity-js/shell#179]
<img width="1197" alt="2018-07-24 16 46 39" src="https://user-images.githubusercontent.com/10687211/43142666-9920cdde-8f61-11e8-98cc-d61f82dc46c4.png">

> I'm running:
>
> - **Parity client version**: 2.0.0-beta
> - **Parity UI version**: 0.3.2
> - **Operating system**: Mac OS
> - **Installed via**:  installer
> - **Fully synchronized**: yes
> - **Network**: ropsten
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

**Comment by axelchalon** [comment]
hi @indigoram89, we've moved the contracts tab to a separate dapp named "Develop contracts". You should find it easily when launching Parity UI

**Comment by indigoram89** [comment]
@axelchalon Wow! I found, thank you! :)
