### ISSUE TITLE
New security token not accepted after switch to Kovan & back

### ISSUE THREAD

**Issue by petri** [parity-js/shell#185]
- **Parity UI version**: 0.3.2
- **Operating system**: MacOS
- **Installed via**: installer
- **Fully synchronized**: yes
- **Network**: mainnet / kovan 
- **I tried to restart both Parity UI and Parity Ethereum client**: yes

I have run Parity UI successfully for a while, connecting to mainnet via current parity stable node (v1.10.6-stable). 

However, I now used the same Parity UI install on another, different parity node connected to Kovan (same parity version). Worked like a charm - but after switching back to the original mainnet node again, Parity UI started asking for a new security token which it then never accepts.

I have ran `parity signer new-token` a multitude of times, confirming copy & paste of the token for sure works correctly. But I always see "Blocked connection from parity://1.ui.parity using invalid token." in the log, and Parity UI keeps asking for the token again and again. I am for sure using the same parity binary for both running the node and generating the security token.

Given I am running parity installed via HomeBrew, and Parity UI installs its own private parity as well (which I never use), I wonder if the parity configurations could be confused?

Please advise.

**Comment by axelchalon** [comment]
hi @petri, have you tried specifying the chain when running `parity signer new-token` ? for example `parity signer new-token --chain mainnet`

**Comment by petri** [comment]
@axelchalon I had not, thanks for pointing it out. But that prompted me to explore what else I might have to pass on to the signer as parameters. It turned out I had forgotten I am using a custom --datadir and passing that to signer, lo and behold it worked! Thank you and apologies for not realizing that before posting here.

**Comment by theBergmann** [comment]
@petri 
Thank you for pointing out, forgetting the path was the reason for me not getting the token, too ...
