### ISSUE TITLE
Parity-ui installs software without permission

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#193]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: none (locally)
> - **Parity UI version**: 0.3.4
> - **Operating system**: Linux
> - **Installed via**: tarball
> - **Fully synchronized**: N/A
> - **Network**: N/A
> - **I tried to restart both Parity UI and Parity Ethereum client**: N/A

When it starts, Parity-ui installs and runs an ETH node.  There is no prompting.  This is bad action from a software.  It is not legal to run a node everywhere.  It is not desirable to install software everyhwere.  There must be an option to download or not.

Now f a user misconfigures SSH tunnel the node downloads automatically.  Never should software automatically install.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by Tbaut** [comment]
I generally agree with you that things should not be hidden, it is clearly stated in the [readme](https://github.com/parity-js/shell) that Parity Ethereum will be installed if not present on the system. As you can also see there too, Parity UI is not actively maintained anymore. Contributions are very welcome.

**Comment by axelchalon** [comment]
agreed, see https://github.com/parity-js/shell/issues/181#issuecomment-410439729
PR/contribution welcome

**Comment by stone212** [comment]
@Tbaut 

> As you can also see there too, Parity UI is not actively maintained anymore.

Interesting.  There was just a release last week and I did not read the Readme after that.

Please tell me what is the supported UI for Parity.  Have they gone back to the webUI in the main Parity program?  On port 8180 I think?

**Comment by stone212** [comment]
Or @axelchalon maybe you will know the answer to the new recommended UI.  (Also The suggestion of the modal is a good one from #181.  It's basically like the suggestion I made in another ticket).

**Comment by Tbaut** [comment]
Parity Technologies wished to focus on base layer architecture. At the time where the UI was built, there was fewer/no alternative. Nowadays, you can use MyCrypto Desktop wallet to manage your account and tokens, Remix for your contract, Metamask to browse web3 websites.. and Parity UI was detached from the "node" to allow the community to take it from there and make it better. More info here: https://paritytech.io/creating-a-lighter-experience/
