### ISSUE TITLE
Parity UI impossible to use with Parity 2.0.1

### ISSUE THREAD

**Issue by matteopey** [parity-js/shell#195]
> I'm running:
>
> - **Parity client version**: 2.0.1
> - **Parity UI version**: 0.3.4
> - **Operating system**: Windows
> - **Installed via**: installer / binaries
> - **Fully synchronized**: yes
> - **Network**: any
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

After starting the Parity node (on any Ethereum network), Parity UI asks for a new token and the node gives this error: `Blocked connection from parity://1.ui.parity using invalid token. `
After creating a new token with the command `parity signer new-token` and supplying it to Parity UI, the node keeps giving the same error, and the UI never starts.

**Comment by Tbaut** [comment]
Please launch the `signer new-token` command with the same flags, used for the node. If you use `--base-path /some/dir --chain mychain.json` you should then launch  `parity signer new-token --base-path /some/dir --chain mychain.json `
