### ISSUE TITLE
Applications tab missing

### ISSUE THREAD

**Issue by holoiii** [parity-js/shell#196]
Where did the applications tab go? It was present in the old parity UI but is longer in this one. I'm trying to access a website that uses web3 but I can't seem to figure out how to do that from within the parity ui.

Thanks!

**Comment by Tbaut** [comment]
I'm sorry to inform you that the web3 browser as well as the chrome extension have been discontinued as there exists many good alternatives. Please find a guide on how to browse a web3 website: https://wiki.parity.io/FAQ#how-to-use-parity-ethereum-chrome-extension-to-browse-a-web3-website
