### ISSUE TITLE
parity-ui tried to download parity even when tunnel exists

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#201]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 0.34
> - **Parity UI version**: 1.11.8
> - **Operating system**: Linux
> - **Installed via**: Parity: .deb | parity-ui: tar
> - **Fully synchronized**: yes
> - **Network**: private
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I start the tunnel with:

` $ ssh -p2211 -L 8545:localhost:8545 -L 8546:localhost:8546 <user>@<hostname> -vv`

Then i start parity-ui

I see that the tunnel is working because I see things in the console like:
`debug1: Local forwarding listening on 127.0.0.1 port 8546.`

`Connection to port 8546 forwarding to localhost port 8546 requested.`

`debug1: channel 6: free: direct-tcpip: listening port 8546 for localhost port 8546, connect from 127.0.0.1 port 39222 to 127.0.0.1 port 8546, nchannels 7`

However immediately after starting parity-ui begins to "fetch" parity.  Removing the files from .config/parity-ui does not change this.

**Comment by stone212** [comment]
Without any explanation it worked after trying about 15 times.  I did not change the tunnel Just CTRL-C and then delete ~/.config/parity-ui every time and then restart parity-ui.  BUT when the UI started it did not show connection to *any* chain and 0/0 peers.  So it was not a success but at least it might help explain the problem?

**Comment by Tbaut** [comment]
Duplicates https://github.com/parity-js/shell/issues/181

**Comment by axelchalon** [comment]
Currently, Parity UI will download Parity if it cannot find Parity in the system, even if it managed to connect. This was done to be able to run `parity signer new-token` programatically. Some improvements ideas here https://github.com/parity-js/shell/issues/181#issuecomment-410439729

**Comment by stone212** [comment]
@Tbaut @axelchalon  This is not a duplicate of #181.  

#181 is a complaint that ParityUI should not download Parity automatically because it is a security risk.

#201 (this one) is a bug because ParityUI is downloading Parity *even when the SSH tunnel exists*.
