### ISSUE TITLE
ParityUI Does Not Recognize SSH Tunnel

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#203]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 0.34
> - **Parity UI version**: 1.11.8
> - **Operating system**: Linux
> - **Installed via**: .deb/tar
> - **Fully synchronized**: yes
> - **Network**: private
> - **I tried to restart both Parity UI and Parity Ethereum client**:yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After creating the tunnel, I start Parity UI.  Parity UI tries to download Parity.  That means it does not recognize the tunnel.  I am expecting Parity UI to give me the UI attached to the node I have the tunnel to.

**Comment by Tbaut** [comment]
Isn't that similar to https://github.com/parity-js/shell/issues/201 that itself is a the same as #181 ?

**Comment by stone212** [comment]
@Tbaut It is the same as #201 which has no relation to #181 but #201was closed becuse someone incorrectly thought it was.

**Comment by stone212** [comment]
@Tbaut Just a short note to re-state that this is not a duplicate of any open issues.  #201 is closed (it shouldn't have been but it was) and #181 is completely different from this issue.

**Comment by stone212** [comment]
I am closing this because I can not re-produce it.  0.3.4 recognizes my SSH tunnel when I invoke:

`ssh -N -L 8180:localhost:8180 -L 8545:localhost:8545 -L 8546:localhost:8546  root@myserver.com`
