### ISSUE TITLE
How to pass CLI parameters when running UI on MacOS?

### ISSUE THREAD

**Issue by DeRain** [parity-js/shell#204]
Hello! A dumb question - how can i pass CLI parameters (rpc path, ws path, etc) when I'm running parity shell on macOS?

**Comment by vstavetski** [comment]
All other flags passed to Parity UI will be passed down to parity when trying to launch it.
For example: for using kovan network I use this command:
`npm run  electron:dev --chain=kovan`

**Comment by DeRain** [comment]
I asked a bit wrong question here. The question was - how to find parity binary when you installing Mac OS application.

I think I found the answer. Just go inside Parity UI.app and you will find Parity UI binary 

```bash
$ cd /Applications/Parity\ UI.app/Contents/MacOS/
$ ./Parity UI --no-run-parity --etc
```

Thank you anyway 👍
