### ISSUE TITLE
Asked for the local Key - Can't confirm the transaction

### ISSUE THREAD

**Issue by MarkLouren** [parity-js/shell#215]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 2.0.6 pairty --light
> - **Parity UI version**: 0.3.4
> - **Operating system**: MacOS 
> - **Installed via**: installer 
> - **Fully synchronized**:  yes
> - **Network**: ethereum ...
> - **I tried to restart both Parity UI and Parity Ethereum client**:  yes -twice
I can't send a transaction - Parity asks for local keys. I don't have them. Where they are stored on Mac or how to solve this issue. Just in case, I don't have vaults, node is fully synch, 
![account_transaction](https://user-images.githubusercontent.com/10350396/46735922-4dfc1580-cca0-11e8-8a03-3f03cd1c3c68.jpg)
_

**Comment by Tbaut** [comment]
Parity UI is not working well together with the latest versions of Parity Ethereum unfortunately. This is known, but since Parity UI is now a community maintained software, it might not get fixed soon.

**Comment by MarkLouren** [comment]
ok, so how can I get access to my wallet without Parity UI? http://127.0.0.1:8180/ host doesn't work anymore. What should I do?

**Comment by Tbaut** [comment]
You can use the JSON key file that  you can find:
- OSX : `~/Library/Application\ Support/io.parity.ethereum/keys/`
- Linux : `~/.local/share/io.parity.ethereum/keys/`
- Windows: `%APPDATA%\Parity\Ethereum\keys`

together with [MyCrypto Desktop app](https://download.mycrypto.com/) for instance.

**Comment by MarkLouren** [comment]
Parity has stopped work on my computer at all(((, so after spending two days trying to fix this issue. I exported private keys from Parity to Metamask and make transaction from Metamask.
