### ISSUE TITLE
How to launch Parity UI ?  (Ubuntu/Linux)

### ISSUE THREAD

**Issue by fireheadman** [Parity-JS/shell#27]
The documentation on Parity UI seems scarce....
I downloaded the deb pkg and installed it..... But I am unsure how to launch it.

Could use a little guidance on this...

**Comment by fireheadman** [comment]
wanted to add... I am on a headless miner, so unsure if this is wanting an Xserver in the background to attach to ?

Each time I launch `parity-ui`   ...I get a return prompt (nothing happens)

**Comment by amaurymartiny** [comment]
Yes, exactly. `parity-ui` is an Electron app, so needs X to be displayed. `parity-ui` is not required to run your local parity node, but it's for people who want an UI to control the node.

There is some doc at https://wiki.parity.io/Parity-Wallet, but I do agree it's scarce. We are working on it.
