### ISSUE TITLE
Cannot install package on Ubuntu Server 17.10

### ISSUE THREAD

**Issue by ravensorb** [Parity-JS/shell#29]
Seems like the current package has a dependency of name of x11 and/or gnome applications.  Any details on why?

**Comment by amaurymartiny** [comment]
`parity-ui` is an Electron app, a GUI to control your local parity node. Therefore it requires X.

You can run a [parity node](https://github.com/paritytech/parity) node with the `parity` command on Ubuntu Server. `parity-ui` (this repo) is the command to launch the GUI, but it's an optional package.

Here is some doc: https://wiki.parity.io/Parity-Wallet
