### ISSUE TITLE
Approved transactions not broadcast

### ISSUE THREAD

**Issue by calfer** [parity-js/shell#33]
OS: MacOS Sierra, updated to the latest

I uninstalled 1.8.5 beta today and installed 1.10.0 node and corresponding UI.  I created a transaction to send from one of my accounts to another using the new UI.  I was prompted for my password, I entered it and a transaction hash was displayed.  However, the account balances were not updating to reflect the transaction.  My node was synced prior to creating the transaction and remained synced during the transaction process.  I waited several minutes.  The transaction was not reflected in the UI or on-chain.  I repeated the transaction twice more since I was only sending to myself.  Still no sign of the transaction.  I then quit the Parity node and UI processes on the Mac and started Parity with the --force-ui flag to try the old browser UI.  I granted the UI access to the accounts when prompted.  The balances were still not reflecting the transaction.  I created the same transaction again using the web UI, entered my password when prompted and the transaction was signed and broadcast successfully.  Immediately following that, several signing requests appears in the web UI, some requesting to transfer the amount equaling that which was just sent successfully and some requesting to send 0.00 value between my accounts.  It took several additional attempts at cancelling these requests before they would disappear from the signing queue.

I have not created any subsequent transactions so the above is the extent of my experience thus far.

**Comment by amaurymartiny** [comment]
Hello @calfer, thanks for your detailed description.

Just to confirm, right after putting your password, you said you saw the transaction hash, which is this box, correct?

![screen shot 2018-03-28 at 10 51 05 am](https://user-images.githubusercontent.com/1293565/38018720-fe8dd8b8-3275-11e8-9bb0-48bb4f201015.png)

If you leave this box open, it'll show you in which block it's included, and the number of confirmations this block has:

![screen shot 2018-03-28 at 10 48 26 am](https://user-images.githubusercontent.com/1293565/38018786-31146554-3276-11e8-8c2f-b1a6818a0cfa.png)

Your account balance is not updated immediately after the transaction, we wait for 6 confirmations before doing it.

Some questions for you:
- Were you fully synced when you created the transactions? The transactions appearing all at once may be that they appeared once you got synced.
- Did you see the 1st screenshot? The 2nd screenshot?

**Comment by calfer** [comment]
amaurymartiny,

I did see the transaction hash box.  However, confirmations were not taking place, thus no progress indicator was visible as in your second image.  My node was fully synced before and during the transaction process according to Parity's status.

I will try to reproduce the issue in the next 24 hours and report back.

**Comment by calfer** [comment]
As a follow up, I sent another transaction between my personal accounts using the new UI.  This time it went off without a hitch.  Perhaps it was just network connectivity issues or some other force preventing my earlier transactions.  All seems well now.

**Comment by amaurymartiny** [comment]
No problem! Feel free to reopen if you manage to repro it.
