### ISSUE TITLE
Parity should be bundled inside the AppImage

### ISSUE THREAD

**Issue by probonopd** [parity-js/shell#41]
Since an [AppImage](https://appimage.org/) is supposed to be self-contained (i.e., have no dependencies other than the target system/distribution), Parity should be bundled inside the AppImage and should be launched before the UI is launched. So that this is never shown:

![](https://user-images.githubusercontent.com/2480569/38416136-5357d0e2-3983-11e8-87b4-88b71f11bfea.png)

AppImage is meant to do away with the need to install anything. One app = one file, just download and run.

**Comment by amaurymartiny** [comment]
Agreed. Our plan is actually to bundle parity inside all the installers on all platforms (not only AppImage), so that one installer installs Parity + Parity UI.

This will be available at v1.11.

**Comment by probonopd** [comment]
If someone could ping me once  1.11 is available I could add this to the AppImageHub central directory of available AppImages. Thanks.
