### ISSUE TITLE
Change to the js directory inside parity/: do you mean json?

### ISSUE THREAD

**Issue by jamesray1** [parity-js/shell#43]
Your readme says:

> Change to the js directory inside parity/

There is no js directory, there's a json directory. https://github.com/paritytech/parity

**Comment by amaurymartiny** [comment]
No, it's not the json directory. The readme unfortunately only applies to parity <1.10. Since that version we've separated the JS and Rust parts.

We're currently writing an updated README.

**Comment by Tbaut** [comment]
https://github.com/parity-js/shell/pull/44
