### ISSUE TITLE
Develop contract error

### ISSUE THREAD

**Issue by norganna** [parity-js/shell#54]
I'm running:

- **Parity client version**: Parity/v1.10.0-beta-0a9d41e-20180320/x86_64-macos/rustc1.24.1
- **Parity UI version**: 0.1.0.237
- **Operating system**: MacOS
- **Installed via**: binaries
- **Fully synchronized**: yes
- **Network**: kovan
- **I tried to restart both Parity UI and Parity Ethereum client**: yes

When attempting to use the Contracts / Develop option in the electrum client, the following error is presented:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' ".
```

**Comment by Tbaut** [comment]
Thanks for your issue @norganna. It should be fixed by https://github.com/paritytech/parity/pull/8204 in the next release.You can also build ([Parity client](https://github.com/paritytech/parity), not UI) from sources.
