### ISSUE TITLE
Transactions not being sent to network for confirmation

### ISSUE THREAD

**Issue by calfer** [parity-js/shell#56]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: Parity v1.10.0-20180320 beta
> - **Parity UI version**: 0.1.0
> - **Operating system**: MacOS High Sierra 10.13.4
> - **Installed via**: installer
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: Yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I created a transaction last Thursday or so to send some ETH between my own accounts.  A transaction hash was created and the transaction window appeared.  However, it was never broadcast to the network and has received zero confirmation as a result.  This transaction window appears each time I restart the Parity UI.  It also appears when I run the old web UI.  I can click on it and it will disappear but it does not show up in the Signer in either UI, either before or after clicking it.  My node has been synced for days but the transaction never broadcasts and persists in limbo across client and OS restarts.

I need to send funds now but I am not sure I should until I can resolve this issue.

Is it possible to cancel a transaction after I've approved it?  How can I get this transaction to broadcast and get confirmed by the network?

**Comment by Tbaut** [comment]
This transaction is most probably in the "queue future" due to a nonce error, and hangs here forever without being broadcast. You can verify this by navigating to your Home>TxQueue Viewer and see in "own transactions".
To clean this list, please run parity with the flag `--no-persistent-txqueue`.

**Comment by calfer** [comment]
Thank you for the quick response.  I started Parity with the flag as you mentioned and the transaction window never showed up so I presume this resolved my issue.
