### ISSUE TITLE
Ui doesn`t display any dapps when client is in light mode

### ISSUE THREAD

**Issue by mr-tron** [parity-js/shell#85]
> I'm running:
>
> - **Parity client version**: 1.10.2-beta
> - **Parity UI version**: v0.1.1-beta
> - **Operating system**: Ubuntu 18.04
> - **Installed via**: x64 deb package from github releases page
> - **Fully synchronized**: yes
> - **Network**: ethereum 
> - **I tried to restart both Parity UI and Parity Ethereum client**:  yes

**actual**: 
White screen. no useful information except sync status
**expected behavior** 
Old good interface with wallets. 
**steps to reproduce** 
new ubuntu 18.04 x64. timezone: utc+2
Install http://d1h4xl4cr1h0mo.cloudfront.net/v1.10.2/x86_64-unknown-linux-gnu/parity_1.10.2_ubuntu_amd64.deb 
https://github.com/parity-js/shell/releases/download/v0.1.1/parity-ui_0.1.1_amd64.deb
run `parity --light` 
run `parity-ui` in over terminal

![image](https://user-images.githubusercontent.com/702560/39645482-66e8b618-4fd0-11e8-84c6-9df94c4620af.png)

**Comment by Tbaut** [comment]
Thanks for logging the issue. The light client is experimental and does not support Dapps, the Parity UI App is now used for both light and full nodes and some improvements can be done. It's not our priority right now though so this feature might not be developed any time soon :)

**Comment by mr-tron** [comment]
I updated client to 1.10.3, waited 2 hours and ui SUDDENLY started work normally.
But now after each restart it randomly work/don`t work. "Don`t work" you can see on first screenshot. 
And working screenshot looking something like this:
![photo_2018-05-09_12-12-33](https://user-images.githubusercontent.com/702560/39812782-ec81aa7e-5385-11e8-9a9b-ddc7a3173c3a.jpg)

**Comment by Tbaut** [comment]
@mr-tron can you please share the error when it doesn't work?

**Comment by Tbaut** [comment]
>How? Another screenshot with openned debug window?

yes

>disable internet access

Well I'd say it's expected to have problem if you don't have any internet acces anymore :)

Feel free to reopen if it happens again (with internet access)
